# -*- coding: utf-8 -*-
import json
import os

ENRICH_MAP = {
    "ability": ("general", "基礎通用", "operation ability", "The technician has the ability to operate this tool.", "該技術員具備操作此機台的能力。"),
    "abnormal": ("quality", "品質異常", "abnormal lot", "Stop the tool when an abnormal lot is detected.", "發現異常批次時立即停機。"),
    "abort": ("machine", "機台操作", "abort the run", "Press abort if an emergency occurs.", "緊急狀況時請按下中止。"),
    "absence": ("workplace", "廠務交接", "absence report", "Inform your supervisor before taking absence.", "請假缺席前請先通知主管。"),
    "acid": ("process", "晶圓製程", "acid tank", "Wear chemical gloves when handling acid.", "處理酸液時請戴化學手套。"),
    "active": ("general", "基礎通用", "active status", "Make sure the recipe is in active status.", "確認配方處於啟動狀態。"),
    "actual": ("general", "基礎通用", "actual yield", "Check the actual yield on the monitor.", "在螢幕上檢查實際良率。"),
    "add": ("general", "基礎通用", "add chemical", "Do not add chemical without authorization.", "未經授權切勿添加化學液。"),
    "adjust": ("machine", "機台操作", "adjust parameter", "Adjust the parameter according to the S.O.P.", "依照 SOP 調整機台參數。"),
    "AI": ("machine", "機台操作", "AI inspection", "AI inspection improves wafer defect detection.", "AI 檢測能提升晶圓缺陷判讀效率。"),
    "air shower": ("process", "晶圓製程", "pass air shower", "Enter the air shower before stepping into the clean room.", "進入無塵室前必須先經過潔淨通道。"),
    "alarm": ("quality", "品質異常", "alarm buzzes", "Call the leader immediately when an alarm buzzes.", "警報響起時請立即通報副理或組長。"),
    "alert": ("quality", "品質異常", "system alert", "Check the system alert message carefully.", "仔細檢查系統發出的警示訊息。"),
    "align": ("machine", "機台操作", "align wafer", "The robot arm will align the wafer automatically.", "機械手臂會自動對齊晶圓中心。"),
    "annually": ("workplace", "廠務交接", "certified annually", "Technicians are re-certified annually.", "技術員每年均需重新通過認證考核。"),
    "area": ("workplace", "廠務交接", "fab area", "Safety glasses are required in this fab area.", "在此廠區範圍內必須配戴護目鏡。"),
    "attach": ("workplace", "廠務交接", "attach label", "Attach the correct label on the cassette.", "在晶圓盒上貼上正確的標籤。"),
    "audit": ("quality", "品質異常", "quality audit", "Follow all standard rules during the quality audit.", "品質稽核期間請遵守所有標準規範。"),
    "automatic": ("machine", "機台操作", "automatic track", "The wafer is transferred by an automatic track.", "晶圓透過天車與自動軌道進行傳送。"),
    "automotive": ("process", "晶圓製程", "automotive chip", "Automotive chips require zero-defect quality.", "車用晶片要求零缺陷的高品質標準。"),
    "available": ("machine", "機台操作", "machine available", "This machine is available for the next run.", "這台機台目前可供下一批次生產使用。"),
    "average": ("general", "基礎通用", "average output", "Maintain the average daily output safely.", "在安全的前提下維持平均每日產量。"),
    "backup": ("workplace", "廠務交接", "backup system", "Switch to the backup system if the primary tool fails.", "若主系統異常請切換至備援系統。"),
    "bank": ("process", "晶圓製程", "wafer bank", "Store finished cassettes in the wafer bank.", "將處理好的晶圓盒暫存至晶圓暫存庫。"),
    "basic": ("general", "基礎通用", "basic knowledge", "Master basic semiconductor knowledge first.", "先掌握半導體與無塵室基礎知識。"),
    "beam": ("machine", "機台操作", "laser beam", "Do not look directly into the laser beam.", "嚴禁直視雷射光束。"),
    "benchmark": ("quality", "品質異常", "benchmark line", "Use this recipe as the quality benchmark.", "將此配方作為品質標準標竿。"),
    "bottle": ("process", "晶圓製程", "chemical bottle", "Dispose of the empty chemical bottle properly.", "請依規妥善回收空化學品瓶罐。"),
    "bottom": ("process", "晶圓製程", "bottom layer", "Inspect the bottom layer of the wafer.", "檢驗晶圓底層的平整度。"),
    "broken": ("quality", "品質異常", "broken wafer", "Stop machine immediately if a broken wafer occurs.", "若發生破片請立即停機隔離。"),
    "cancel": ("machine", "機台操作", "cancel command", "Cancel the command if recipe name is incorrect.", "若配方名稱錯誤請立即取消指令。"),
    "card": ("workplace", "廠務交接", "ID card", "Always wear your company ID card in the fab.", "在廠內請務必隨身配戴識別證。"),
    "cart": ("process", "晶圓製程", "transport cart", "Push the transport cart slowly in the hallway.", "在走廊推運送推車時請減速慢行。"),
    "cassette": ("process", "晶圓製程", "load cassette", "Load the cassette into the stocker port.", "將晶圓盒裝載至儲存櫃載入端口。"),
    "center": ("machine", "機台操作", "wafer center", "Align the robot blade with the wafer center.", "讓機械手臂承載托盤對準晶圓中心。"),
    "certify": ("workplace", "廠務交接", "certify operator", "The trainer will certify the new operator.", "訓練員將考核並認證新進操作員。"),
    "change": ("machine", "機台操作", "change recipe", "Confirm lot ID before you change the recipe.", "更改配方前請務必核對批號。"),
    "chart": ("quality", "品質異常", "control chart", "Review the SPC control chart every hour.", "每小時檢視一次 SPC 管制圖趨勢。"),
    "check": ("quality", "品質異常", "double check", "Double check the lot number with the run-card.", "與流程卡仔細雙重覆核批號。"),
    "chemical": ("process", "晶圓製程", "chemical waste", "Separate chemical waste into designated tanks.", "化學廢液必須分流倒入專用儲槽。"),
    "chip": ("process", "晶圓製程", "silicon chip", "Each wafer contains hundreds of silicon chips.", "每一片晶圓包含數百個晶片晶粒。"),
    "choose": ("general", "基礎通用", "choose option", "Choose the right option on the touch screen.", "在觸控螢幕上選擇正確的操作選項。"),
    "clean": ("process", "晶圓製程", "clean surface", "Keep the load port surface completely clean.", "保持裝載端口表面完全清潔無塵。"),
    "clean chamber": ("machine", "機台操作", "clean chamber cycle", "Run a clean chamber cycle after twenty runs.", "每生產二十批後需執行腔體清潔程序。"),
    "clear": ("general", "基礎通用", "clear message", "Clear the alarm message after solving the issue.", "排除問題後在系統上清除警報訊息。"),
    "collect": ("general", "基礎通用", "collect data", "Collect process data for the shift report.", "收集製程參數數據以供交接報告使用。"),
    "color": ("quality", "品質異常", "color indicator", "Green color indicates normal operating status.", "綠色燈號表示機台處於正常運轉狀態。"),
    "comment": ("workplace", "廠務交接", "shift comment", "Leave a detailed comment in the log sheet.", "在工作日誌中留下詳細的交接備註。"),
    "company": ("workplace", "廠務交接", "company policy", "Follow TSMC company safety policies strictly.", "嚴格遵守台積電公司工安與各項規範。"),
    "complete": ("general", "基礎通用", "complete run", "Wait until the machine completes the entire run.", "靜候機台完整執行完畢該生產流程。"),
    "computer": ("machine", "機台操作", "host computer", "Upload the measurement results to the host computer.", "將量測結果上傳至主電腦伺服器。"),
    "concern": ("quality", "品質異常", "safety concern", "Report any safety concern to your leader.", "若有任何工安疑慮請立即向副理回報。"),
    "confidential": ("workplace", "廠務交接", "strictly confidential", "All fab manufacturing data is strictly confidential.", "所有晶圓廠製程數據均屬高度機密。"),
    "confirm": ("quality", "品質異常", "confirm lot ID", "Confirm the lot ID before pushing the start button.", "按下啟動鈕前務必核對確認批號。"),
    "contamination": ("process", "晶圓製程", "prevent contamination", "Wear face masks to prevent particle contamination.", "配戴口罩以避免微塵粒子汙染晶圓。"),
    "continue": ("machine", "機台操作", "continue process", "Check equipment status before you continue.", "繼續運作前請再次確認機台狀態正常。"),
    "control": ("machine", "機台操作", "temperature control", "Maintain precise temperature control in the furnace.", "在爐管製程中維持精確的溫度控制。"),
    "copy": ("general", "基礎通用", "copy file", "Do not copy unauthorized files on the terminal.", "機台終端機嚴禁複製未經許可的檔案。"),
    "count": ("general", "基礎通用", "wafer count", "Check that the wafer count equals 25.", "確認晶圓盒內的片數是否整卡滿 25 片。"),
    "customer": ("workplace", "廠務交接", "customer wafer", "Handle customer wafers with extra care.", "搬運與處理客戶晶圓時務必格外小心。"),
    "cycle": ("process", "晶圓製程", "clean cycle", "Do not interrupt the automated clean cycle.", "請勿中途中斷自動清洗循環。"),
    "cycle time": ("process", "晶圓製程", "reduce cycle time", "Optimize workflow to reduce wafer cycle time.", "最佳化作業流程以縮短晶圓生產週期。"),
    "daily": ("workplace", "廠務交接", "daily meeting", "Attend the daily shift meeting on time.", "準時出席每日交接晨會或夕會。"),
    "data": ("general", "基礎通用", "log data", "Save the inspection log data immediately.", "立即將量測與檢驗數據存檔備份。"),
    "date": ("general", "基礎通用", "due date", "Verify the expiration date of the chemical.", "確認化學藥劑的有效保存期限。"),
    "decline": ("quality", "品質異常", "yield decline", "Investigate causes if daily yield shows decline.", "良率出現下滑時需立即追查異常原因。"),
    "defect": ("quality", "品質異常", "defect inspection", "Inspect wafer surface for any visual defect.", "檢查晶圓表面是否有刮傷或任何微外觀缺陷。"),
    "delay": ("workplace", "廠務交接", "production delay", "Report equipment issues to avoid production delay.", "即時回報機台障礙以避免生產延遲。"),
    "delete": ("general", "基礎通用", "delete recipe", "Never delete recipe files from the machine.", "絕不可隨意刪除機台內的配方檔案。"),
    "diffusion": ("process", "晶圓製程", "diffusion area", "Diffusion furnace operates at very high temperatures.", "擴散製程區的高溫爐管處於極高溫度。"),
    "document": ("workplace", "廠務交接", "standard document", "Follow the operational standard document.", "所有操作步驟均須參照標準作業文件。"),
    "dry": ("process", "晶圓製程", "spin dry", "The wafer is spun dry after chemical rinse.", "晶圓經化學清洗後會進行旋轉甩乾。"),
    "emergency": ("quality", "品質異常", "emergency exit", "Know the location of every emergency exit.", "牢記無塵室內各個緊急逃生出口位置。"),
    "emergency stop": ("machine", "機台操作", "press emergency stop", "Press emergency stop in case of mechanical jam.", "機台發生機械卡死時立即拍下急停鈕。"),
    "engineer": ("workplace", "廠務交接", "process engineer", "Contact the process engineer to release hold lots.", "聯絡製程工程師協助解批卡住的貨。"),
    "enhance": ("quality", "品質異常", "enhance quality", "Continuous checks enhance overall yield and quality.", "持續點檢有助於提升整體良率與品質。"),
    "enter": ("workplace", "廠務交接", "enter clean room", "Put on booties before you enter the gowning room.", "進入更衣室前請先套上鞋套。"),
    "environment": ("process", "晶圓製程", "fab environment", "Maintain strict humidity in the fab environment.", "廠房環境需保持嚴格的恆溫恆濕控制。"),
    "equipment": ("machine", "機台操作", "equipment status", "Verify that the equipment is green before loading.", "上貨前確認機台燈號呈現綠色可生產。"),
    "error": ("quality", "品質異常", "error code", "Write down the error code displayed on screen.", "抄寫記錄螢幕上顯示的異常錯誤代碼。"),
    "etching": ("process", "晶圓製程", "etching process", "Dry etching removes material from the wafer surface.", "乾式蝕刻製程能精準剝除晶圓表面膜層。"),
    "EUV / extreme ultraviolet": ("process", "晶圓製程", "EUV lithography", "EUV lithography produces advanced node chips.", "極紫外光微影技術用於生產最先進製程晶片。"),
    "event": ("quality", "品質異常", "event log", "Record every tool down event into the system.", "將機台當機與停機事件詳實登錄系統。"),
    "execute": ("machine", "機台操作", "execute command", "Execute the batch command after confirmation.", "覆核無誤後方可執行批次加載指令。"),
    "exit": ("workplace", "廠務交接", "emergency exit", "Keep the emergency exit path clear of carts.", "保持緊急疏散走道順暢，嚴禁堆放推車。"),
    "fault": ("quality", "品質異常", "machine fault", "Technician called maintenance for machine fault.", "機台發生硬體故障，技術員已聯絡設備課。"),
    "find": ("general", "基礎通用", "find root cause", "Engineers work to find the root cause of defect.", "工程師與技術員通力合作找出缺陷真因。"),
    "floor": ("process", "晶圓製程", "raised floor", "Cables and pipes run beneath the fab raised floor.", "無塵室高架地板下方鋪設了管線與電纜。"),
    "focus": ("machine", "機台操作", "laser focus", "Calibrate the laser focus before exposure.", "曝光前需精準校正雷射對焦焦點。"),
    "follow": ("workplace", "廠務交接", "follow SOP", "Always follow the SOP without skipping steps.", "嚴格遵守標準作業程序，不可跳過任何步驟。"),
    "freeze": ("machine", "機台操作", "screen freeze", "Reboot the terminal if the UI screen freezes.", "若控制面板畫面當機凍結請回報處理。"),
    "full": ("general", "基礎通用", "cassette full", "The cassette is full with 25 silicon wafers.", "該晶圓盒目前已裝滿 25 片完整晶圓。"),
    "function": ("machine", "機台操作", "safety function", "Test the interlock safety function regularly.", "定期檢測機台互鎖安全防護機能。"),
    "gas": ("process", "晶圓製程", "specialty gas", "Check the specialty gas pressure gauges daily.", "每日例行抄檢特殊製程氣體之壓力表數值。"),
    "glass": ("process", "晶圓製程", "safety glasses", "Put on safety glasses before pouring liquid.", "傾倒藥水前務必戴好防護面罩或護目鏡。"),
    "gloves": ("process", "晶圓製程", "nitrile gloves", "Change clean room gloves if tears appear.", "無塵室手套若有磨損或破損請立即更換。"),
    "grade": ("quality", "品質異常", "product grade", "Sort the finished chips according to product grade.", "依照產品品質等級將晶片分類儲存。"),
    "green": ("machine", "機台操作", "green light", "Machine is ready to run when the green light is on.", "綠燈亮起表示機台處於備便可生產狀態。"),
    "group": ("workplace", "廠務交接", "module group", "Coordinate tasks within your module group.", "在所屬課別模組小組內緊密配合工作。"),
    "handle": ("machine", "機台操作", "handle wafer", "Handle the wafer only with designated vacuum wands.", "僅可使用專用真空吸筆拿取晶圓邊緣。"),
    "hard-disk": ("machine", "機台操作", "system hard-disk", "System logs are stored on the local hard-disk.", "機台運作日誌存儲於機載硬碟中。"),
    "heavy": ("workplace", "廠務交接", "heavy equipment", "Use ergonomic lifting when moving heavy boxes.", "搬運較重之零件箱體時請善用符合人體工學姿勢。"),
    "helmet": ("workplace", "廠務交接", "safety helmet", "Wear a safety helmet during tool maintenance.", "機台歲修保養施工期間請務必配戴工程安全帽。"),
    "help": ("workplace", "廠務交接", "ask for help", "Ask your shift buddy for help when in doubt.", "若對步驟有疑慮時，立即向組長或同仁求助。"),
    "hold": ("quality", "品質異常", "hold lot", "Put the lot on hold until inspection finishes.", "暫停該批次貨件運送，等待品檢判定。"),
    "hole": ("quality", "品質異常", "contact hole", "Verify that the contact hole has no residue.", "檢測接觸孔洞底層是否有任何殘留物。"),
    "hot": ("process", "晶圓製程", "hot surface", "Caution: Hot surface warning on furnace tubes.", "注意：高溫爐管外壁具有灼熱高溫警示。"),
    "impact": ("quality", "品質異常", "yield impact", "Assess whether particle count has a yield impact.", "評估落塵微粒增加是否會對良率造成衝擊。"),
    "improve": ("quality", "品質異常", "improve yield", "Adhere to clean procedures to improve yield.", "落實無塵室清潔標準作業以提升良率。"),
    "inform": ("workplace", "廠務交接", "inform supervisor", "Inform your supervisor of any tool abnormality.", "機台發生任何異常請第一時間回報主管。"),
    "information": ("general", "基礎通用", "lot information", "Check lot information on the MES terminal.", "在製造執行系統 (MES) 終端機上核對貨批資訊。"),
    "inhibition": ("machine", "機台操作", "tool inhibition", "Tool inhibition prevents loading wrong recipes.", "機台互鎖防呆機制可防止載入錯誤配方。"),
    "input": ("machine", "機台操作", "input parameter", "Input the parameter values specified by S.O.P.", "依照 SOP 規定數值精確輸入製程參數。"),
    "inspect": ("quality", "品質異常", "inspect cassette", "Inspect cassette edges for physical scratches.", "仔細目視檢查晶圓盒外框是否有磨損刮傷。"),
    "inspection": ("quality", "品質異常", "wafer inspection", "Send samples for microscopic wafer inspection.", "抽樣晶圓送往顯微鏡進行高解析外觀檢驗。"),
    "instruction": ("workplace", "廠務交接", "follow instruction", "Carry out each step following the work instruction.", "遵照作業指引卡上的每一步驟確實操作。"),
    "Internet": ("workplace", "廠務交接", "intranet access", "Fab workstations connect only to internal network.", "廠區機台工作站僅限連線內部管制網路。"),
    "interview": ("workplace", "廠務交接", "job interview", "Explain your shift adaptability during the interview.", "面試時具體展現您對四班二輪與細心度的適應力。"),
    "issue": ("quality", "品質異常", "report issue", "Log the mechanical issue in the online system.", "將機台機械異常問題即刻通報登錄系統。"),
    "job": ("workplace", "廠務交接", "shift job", "Technician job demands focus and adherence to rules.", "技術員工作要求高度專注並嚴格遵循規範。"),
    "keep": ("workplace", "廠務交接", "keep clean", "Keep your working station orderly and clean.", "隨時保持機台機台工作站整齊與乾淨。"),
    "keyboard": ("machine", "機台操作", "clean keyboard", "Cover the keyboard with clean protective film.", "機台鍵盤外部需包覆專用抗靜電保護膜。"),
    "label": ("workplace", "廠務交接", "barcode label", "Scan the barcode label before loading wafers.", "將晶圓盒上架前請先用讀碼槍掃描條碼標籤。"),
    "laboratory": ("process", "晶圓製程", "analytical laboratory", "Send chemical samples to the laboratory for analysis.", "將化學品樣品送至分析實驗室檢驗濃度。"),
    "leader": ("workplace", "廠務交接", "shift leader", "Report attendance directly to your shift leader.", "班前請先向值班帶線組長報到。"),
    "learn": ("workplace", "廠務交接", "learn SOP", "Take time to learn every step in the new SOP.", "花時間認真熟讀並學會新修訂的 SOP 流程。"),
    "level": ("general", "基礎通用", "liquid level", "Check the liquid level sensor before starting.", "啟動前請先確認化學槽液位感測器正常。"),
    "lift": ("machine", "機台操作", "elevator lift", "The cassette lift moves wafers smoothly up.", "機台內部升降機構能平穩托起晶圓盒。"),
    "light": ("quality", "品質異常", "warning light", "Amber warning light means tool needs operator attention.", "黃色警示燈代表機台需要技術員介入處理。"),
    "line": ("process", "晶圓製程", "production line", "Clean room production line runs twenty-four hours.", "無塵室晶圓生產線採全年無休二十四小時運轉。"),
    "link": ("machine", "機台操作", "MES link", "Ensure the tool is online with active MES link.", "確認機台通訊處於連線中且 MES 連結正常。"),
    "liquid": ("process", "晶圓製程", "cleaning liquid", "Pump cleaning liquid into the rinse chamber.", "將高純度清洗液泵入清洗腔體內。"),
    "list": ("workplace", "廠務交接", "checklist", "Check off every item on the daily checklist.", "逐一勾選日常機台點檢表上的所有檢驗項目。"),
    "lithography": ("process", "晶圓製程", "lithography track", "Lithography process transfers patterns onto wafer.", "黃光微影製程負責將電路圖案轉移至晶圓上。"),
    "load": ("machine", "機台操作", "load wafer", "Load the wafer cassette onto port one carefully.", "小心將晶圓盒載入至第一號進料端口。"),
    "loading": ("machine", "機台操作", "loading port", "Do not block the loading port with spare carts.", "請勿將備用推車停放在機台裝載口前方阻擋。"),
    "lobby": ("workplace", "廠務交接", "fab lobby", "Visitors must register at the reception lobby.", "外賓必須在晶圓廠一樓大廳櫃檯完成換證登記。"),
    "location": ("workplace", "廠務交接", "tool location", "Verify the exact location of the target stocker.", "核對目標自動儲存櫃在無塵室中的確切代號位置。"),
    "lock": ("machine", "機台操作", "door lock", "Safety door lock engages while the robot moves.", "當內部機械手臂動作時，機台安全防護門會自動上鎖。"),
    "log sheet": ("workplace", "廠務交接", "sign log sheet", "Sign the log sheet after completing shift handover.", "完成交接盤點後，請在班別工作日誌上簽名覆核。"),
    "lose": ("quality", "品質異常", "lose track", "Scan barcodes carefully so system never loses track.", "確實刷讀條碼，確保系統不會遺漏追蹤任何一批貨。"),
    "lot": ("process", "晶圓製程", "wafer lot", "Each wafer lot typically contains twenty-five wafers.", "一個標準晶圓批通常包含二十五片晶圓。"),
    "machine": ("machine", "機台操作", "machine status", "Check machine status before pressing the run key.", "按下啟動鍵前，務必再三檢視機台狀態。"),
    "maintain": ("machine", "機台操作", "maintain tool", "Technicians and engineers maintain tool uptime.", "技術員與設備工程師通力維持機台高妥善運轉率。"),
    "manual": ("machine", "機台操作", "manual mode", "Switch to manual mode only when authorized.", "僅在工程師授權下才可將機台切換至手動模式。"),
    "manufacture": ("process", "晶圓製程", "manufacture chips", "TSMC manufactures world-leading semiconductor chips.", "台積電致力於製造全球最領先的半導體晶片。"),
    "mark": ("quality", "品質異常", "alignment mark", "Robot optical sensor scans the alignment mark.", "機械手臂之光學感測器負責辨讀對齊標記。"),
    "mask": ("process", "晶圓製程", "photomask", "Inspect the photomask for particles before exposure.", "曝光前仔細檢查光罩表面是否有落塵微粒。"),
    "material": ("process", "晶圓製程", "raw material", "Check the raw material lot number before replenishment.", "化學耗材更換前請核對原材料之生產批號。"),
    "measure": ("quality", "品質異常", "measure thickness", "Measure oxide thickness at five points on the wafer.", "在晶圓表面量測五點氧化層膜厚均勻度。"),
    "mechanical": ("machine", "機台操作", "mechanical arm", "Keep hands clear while the mechanical arm operates.", "機械手臂運動過程中嚴禁伸手伸入安全光柵內。"),
    "merge": ("process", "晶圓製程", "merge lots", "Merge split lots according to engineer instructions.", "依照工程師開立之批單指示進行合批操作。"),
    "message": ("machine", "機台操作", "system message", "Read the on-screen system message before proceeding.", "進行下一步操作前請詳閱螢幕上的系統提示訊息。"),
    "metal": ("process", "晶圓製程", "metal deposition", "Thin metal layers form interconnects on the wafer.", "晶圓金屬薄膜沈積製程形成微米級電路導線。"),
    "miss-operation": ("quality", "品質異常", "zero miss-operation", "Follow the double-check procedure to avoid miss-operation.", "嚴格落實覆核防呆程序，追求零誤動作。"),
    "monitor": ("machine", "機台操作", "monitor screen", "Watch the monitor screen for recipe progress.", "在操作螢幕上即時監視配方加工進度條。"),
    "monthly": ("workplace", "廠務交接", "monthly maintenance", "The equipment undergoes monthly preventive maintenance.", "機台每個月均需定期執行停機預防保養 (PM)。"),
    "more": ("general", "基礎通用", "more wafers", "Load more wafers when the input port is clear.", "當進料端口淨空後即可裝載下一批晶圓。"),
    "move": ("machine", "機台操作", "robot move", "Wait until the robot completes its move.", "請靜待機械手臂完整歸位並停止動作。"),
    "new": ("general", "基礎通用", "new recipe", "Test the new recipe under engineer supervision.", "在工程師陪同指導下測試新版配方。"),
    "normal": ("quality", "品質異常", "normal operation", "Confirm that vacuum pressure returns to normal.", "確認腔體內部真空度已恢復至正常規格值。"),
    "note": ("workplace", "廠務交接", "handover note", "Write down tool remarks in the handover note.", "將機台微異狀詳記於交接備忘錄提供下一班參考。"),
    "notice": ("workplace", "廠務交接", "safety notice", "Read the safety notice posted near the acid bench.", "詳讀張貼於化學清洗機台旁的工安注意事項公告。"),
    "number": ("general", "基礎通用", "lot number", "Type in the exact lot number on the keyboard.", "在鍵盤上精確輸入欲加工之晶圓批號。"),
    "office": ("workplace", "廠務交接", "department office", "Handover meetings are held in the department office.", "每日交接會均於部課辦公室內準時召開。"),
    "off-line": ("machine", "機台操作", "tool off-line", "Set tool off-line before technicians start maintenance.", "技術員開始執行保養前，請先將機台設為離線。"),
    "on time": ("workplace", "廠務交接", "arrive on time", "Always arrive on time for shift changeover.", "輪班交接班時請務必提前準時抵達無塵室。"),
    "on-line": ("machine", "機台操作", "bring on-line", "Bring tool on-line after engineering approves release.", "工程師簽核放行後，即可將機台重新切回在線生產。"),
    "operation": ("machine", "機台操作", "standard operation", "Execute standard operation following every single step.", "遵照規範落實每一步標準作業，絕不圖快省略。"),
    "output": ("general", "基礎通用", "daily output", "Shift team worked safely to achieve the target daily output.", "輪班團隊在安全前提下齊心達成每日目標產能。"),
    "oven": ("process", "晶圓製程", "bake in oven", "Bake the photoresist in the oven at specified temperature.", "在烘烤箱中以設定溫度對光阻進行軟烤硬烤。"),
    "over time": ("workplace", "廠務交接", "work over time", "Over time hours are arranged according to labor regulations.", "加班出勤均依勞基法規定並預先安排確認。"),
    "page": ("general", "基礎通用", "SOP page", "Turn to page three of the equipment manual.", "翻閱至機台操作手冊第三頁查看排除步驟。"),
    "paper": ("process", "晶圓製程", "clean room paper", "Use only special clean room paper inside the fab.", "無塵室內僅能使用不起塵的專用無塵紙書寫。"),
    "parameter": ("machine", "機台操作", "recipe parameter", "Verify that every recipe parameter matches the spec.", "核對各項配方參數是否與規格書嚴格相符。"),
    "part": ("machine", "機台操作", "spare part", "Confirm the serial number of the replacement spare part.", "更換機台零件前核對備品序號。"),
    "particle": ("quality", "品質異常", "particle count", "High particle count triggers an automatic quality hold.", "微塵粒子超標將自動觸發晶圓品質暫停管制作業。"),
    "pass": ("quality", "品質異常", "pass inspection", "Only wafers that pass inspection move to next step.", "唯有通過品質檢驗的晶圓才能放行至下個製程站點。"),
    "password": ("machine", "機台操作", "login password", "Never share your system login password with others.", "絕不可將個人的機台登入密碼借調給他人使用。"),
    "perfect": ("quality", "品質異常", "perfect yield", "Dedicated team achieved perfect yield on sample run.", "技術員細心操作使試產批次達成了完美良率。"),
    "personal": ("workplace", "廠務交接", "personal safety", "Personal safety is the top priority in the fab.", "在晶圓廠內，同仁的人身安全永遠是第一優先。"),
    "phase": ("general", "基礎通用", "ramp-up phase", "Follow strict guidelines during the new fab ramp-up phase.", "新廠產能爬坡擴產階段須嚴格遵守標準作業。"),
    "photo": ("process", "晶圓製程", "photo area", "Yellow lighting protects sensitive photoresist in photo area.", "黃光微影區採用黃色光源以保護光阻不被感光。"),
    "plan": ("workplace", "廠務交接", "shift plan", "Review the daily shift plan before distributing lots.", "派工前先審視當班生產計畫與排程目標。"),
    "plus": ("general", "基礎通用", "plus or minus", "Thickness tolerance is plus or minus five angstroms.", "膜厚容許公差為正負五個埃 (Angstrom)。"),
    "pod": ("process", "晶圓製程", "FOUP pod", "Transport FOUP pod with both hands holding bottom.", "雙手搬運晶圓傳送盒 (FOUP) 時請托住底部兩側。"),
    "point": ("general", "基礎通用", "key point", "Remember the key safety point during chemical hookup.", "牢記化學管路接管作業時的各項工安重點。"),
    "position": ("machine", "機台操作", "home position", "The robot arm returned safely to its home position.", "機械手臂已安全平穩回歸機械原點位置。"),
    "positive": ("general", "基礎通用", "positive attitude", "Keep a positive and responsible attitude toward quality.", "對產品品質保持正面積極與高度負責的態度。"),
    "postpone": ("workplace", "廠務交接", "postpone maintenance", "Do not postpone scheduled preventive maintenance.", "定期排定的預防保養作業不可無故拖延推遲。"),
    "power": ("machine", "機台操作", "power switch", "Do not toggle main power switch without supervisor signoff.", "未經副理級主管簽核，嚴禁擅自切換主電源總開關。"),
    "practice": ("workplace", "廠務交接", "good practice", "Labeling containers clearly is a good safety practice.", "將容器清楚張貼標籤是落實工安的良好典範實踐。"),
    "prepare": ("workplace", "廠務交接", "prepare tool", "Prepare cleaning swabs before opening the chamber door.", "開啟機台真空腔體門前，先備妥專用無塵擦拭布。"),
    "press": ("machine", "機台操作", "press button", "Press the start button only after double-checking.", "完成兩道防呆覆核手續後，才可按下啟動按鈕。"),
    "pressure": ("machine", "機台操作", "chamber pressure", "Chamber pressure must reach high vacuum before processing.", "進料加工前，腔體內部壓力必須抽至高真空狀態。"),
    "preview": ("machine", "機台操作", "preview recipe", "Preview the recipe settings on the screen first.", "先在終端螢幕上預覽配方步驟設定是否正確。"),
    "price": ("general", "基礎通用", "equipment price", "Advanced semiconductor equipment has high market price.", "先進半導體製程機台價值極其昂貴，操作需萬分小心。"),
    "print": ("workplace", "廠務交接", "print run-card", "Print a new run-card if the barcode becomes blurred.", "條碼若出現髒污磨損，請立即重新列印新流程卡。"),
    "priority": ("workplace", "廠務交接", "hot lot priority", "Give super hot run lots the highest tool priority.", "優先將機台產能提供給最急件特急貨批生產。"),
    "process": ("process", "晶圓製程", "semiconductor process", "Each semiconductor process requires precise temperature.", "每道半導體製程都需要精密的溫度與壓力控制。"),
    "product": ("process", "晶圓製程", "finished product", "Keep finished product cassettes securely locked.", "已產出之成品晶圓盒應穩妥鎖固於儲存櫃中。"),
    "protect": ("workplace", "廠務交接", "protect wafer", "Wear clean room garments to protect wafers from dust.", "確實穿著無塵衣以保護晶圓免受微塵落塵危害。"),
    "purge": ("machine", "機台操作", "nitrogen purge", "Purge the loadlock chamber with ultra-pure nitrogen.", "以超高純度氮氣對進出料載入腔體進行氣體吹掃置換。"),
    "push": ("workplace", "廠務交接", "push cart", "Push the FOUP cart with two hands in designated lanes.", "雙手推運晶圓推車並行駛於無塵室專用推車道。"),
    "quality": ("quality", "品質異常", "quality first", "In TSMC manufacturing culture, quality always comes first.", "在台積電製造文化中，品質與紀律永遠擺在第一位。"),
    "quantity": ("general", "基礎通用", "wafer quantity", "Confirm wafer quantity matches the dispatch sheet.", "確認晶圓實體片數與系統派工單上數量完全相符。"),
    "rate": ("general", "基礎通用", "sampling rate", "Increase inspection sampling rate when defect count rises.", "當異常數量增加時，應提高品檢抽樣頻率。"),
    "re-certify": ("workplace", "廠務交接", "re-certify skill", "Technicians re-certify their operation skills periodically.", "技術員定期需重新參加技能檢定考核以維持合格認證。"),
    "recipe": ("machine", "機台操作", "select recipe", "Always double check the recipe name before starting run.", "上機啟動前務必雙重覆核配方代碼名稱是否無誤。"),
    "record": ("workplace", "廠務交接", "record anomaly", "Record every tool anomaly immediately in the e-log.", "將機台微幅異常記錄詳實登載於電子交接紀錄簿中。"),
    "recover": ("machine", "機台操作", "tool recover", "Perform manual homing to recover the jammed robot.", "執行手臂手動復歸程序以使卡滯機械結構恢復正常。"),
    "release": ("workplace", "廠務交接", "release lot", "Wait for QC engineer to release the held lot.", "靜待品管工程師於線上系統完成簽核放行動作。"),
    "remark": ("workplace", "廠務交接", "add remark", "Add a detailed remark when transferring WIP to next shift.", "交接在製品 WIP 時請詳細加註機台目前狀況。"),
    "remind": ("workplace", "廠務交接", "remind buddy", "Remind your buddy to wear safety goggles near chemicals.", "在化學酸槽旁主動提醒身旁同仁確實戴上防護鏡。"),
    "remove": ("machine", "機台操作", "remove cassette", "Remove the cassette only after the green unload lamp lights.", "待卸料指示綠燈亮起後，方可將晶圓盒取下。"),
    "repair": ("machine", "機台操作", "repair tool", "Call equipment engineers to repair damaged vacuum seals.", "聯絡設備工程人員更換並維修老化的真空密封橡膠環。"),
    "report": ("workplace", "廠務交接", "report immediately", "Report any chemical leak immediately to the control center.", "若察覺任何微量化學品洩漏，請立即通報應變中心。"),
    "reset": ("machine", "機台操作", "reset alarm", "Investigate root cause before you reset the alarm.", "在按下復歸鍵清除警報前，務必先確認異常發生原因。"),
    "rework": ("quality", "品質異常", "rework wafer", "Engineer ordered rework on photoresist coating error.", "針對光阻塗布厚度異常之晶圓批開立重工清洗指令。"),
    "route": ("process", "晶圓製程", "process route", "Wafers move along a predefined process route.", "晶圓依照系統預先定義之工藝路線順序進行各站加工。"),
    "rule": ("workplace", "廠務交接", "clean room rule", "Follow every clean room rule strictly at all times.", "無塵室各項工安與行為守則於任何時刻均須嚴格遵循。"),
    "run": ("machine", "機台操作", "start run", "Check all interlocks before you start the production run.", "開始批次生產運行前，確認各安全防護開關皆已就位。"),
    "run-card": ("workplace", "廠務交接", "check run-card", "Run-card specifies the recipe and target thickness.", "流程卡詳細註明了當站規定配方與目標膜厚加工值。"),
    "S.O.P / Standard Operating Procedures": ("workplace", "廠務交接", "strict S.O.P", "Strict S.O.P adherence ensures zero-defect manufacturing.", "嚴格遵守標準作業程序 (SOP) 是零缺陷製造的基石。"),
    "safe": ("workplace", "廠務交接", "stay safe", "Follow safety protocols to keep everyone in the fab safe.", "落實各項工安防護步驟，確保廠內全體同仁人身安全。"),
    "same": ("general", "基礎通用", "same lot", "All wafers in the same lot share identical parameters.", "同一批晶圓內的二十五片晶圓共享完全相同的製程參數。"),
    "save": ("general", "基礎通用", "save configuration", "Save the parameter configuration before closing window.", "在關閉機台設定視窗前，請務必點擊儲存變更。"),
    "scrap": ("quality", "品質異常", "scrap wafer", "Severe crack on wafer resulted in unavoidable scrap.", "晶圓發生嚴重碎裂，經工程師判定無可挽回必須報廢。"),
    "scratch": ("quality", "品質異常", "wafer scratch", "Avoid touching wafer surface to prevent micro scratch.", "嚴禁徒手接觸晶圓表面以避免造成肉眼不可見的微刮傷。"),
    "screen": ("machine", "機台操作", "touch screen", "Wipe the touch screen only with approved clean room wipes.", "僅可使用指定抗靜電無塵擦拭布清潔操作螢幕。"),
    "select": ("machine", "機台操作", "select menu", "Select the correct lot number from the on-screen menu.", "在螢幕操作選單中正確點選當前欲生產之批號。"),
    "semiconductor": ("process", "晶圓製程", "semiconductor fab", "TSMC operates the most advanced semiconductor fabs.", "台積電擁有並營運著全球技術最頂尖的半導體晶圓廠。"),
    "service": ("workplace", "廠務交接", "vendor service", "Vendor service technicians wear distinct guest badges.", "駐廠廠商工程師入廠檢修時均配戴專屬外賓識別證。"),
    "sheet": ("workplace", "廠務交接", "inspection sheet", "Sign your employee number on the paper inspection sheet.", "在紙本巡檢表上工整簽上員工工號以示確認負責。"),
    "shift": ("workplace", "廠務交接", "day shift", "Technicians rotate smoothly between day shift and night shift.", "技術員依排班表順暢輪替於日班與夜班之間。"),
    "show": ("general", "基礎通用", "show result", "The monitor will show measurement result in green text.", "檢驗機台螢幕將以綠色文字顯示通過之量測結果。"),
    "shuttle": ("workplace", "廠務交接", "company shuttle", "Take the company shuttle bus between fabs safely.", "往返不同廠區與宿舍之間請搭乘公司免費交通接駁車。"),
    "skip": ("workplace", "廠務交接", "never skip steps", "Never skip steps even when rushing for daily quota.", "即使趕進度也絕不可擅自跳過或省略任何一個 SOP 步驟。"),
    "sorter": ("machine", "機台操作", "wafer sorter", "Wafer sorter transfers wafers between two cassettes.", "晶圓挑片機在不同晶圓盒之間自動分揀傳送晶圓。"),
    "source": ("process", "晶圓製程", "light source", "Check the output power level of the exposure light source.", "檢查黃光曝光光源之輸出能量等級是否在容許範圍內。"),
    "Spec. / specification": ("quality", "品質異常", "out of spec", "Any parameter out of spec must be flagged immediately.", "任何量測數值超出規格 (OOS) 時均須立即拉紅線報備。"),
    "speed": ("machine", "機台操作", "rotation speed", "Spindle motor rotation speed reached five thousand RPM.", "旋轉主軸馬達轉速穩定達到設定之每分鐘五千轉。"),
    "split": ("process", "晶圓製程", "split lot", "Split five wafers from the main lot for testing.", "依照工程需求從主批中分拆出五片晶圓作為實驗監控批。"),
    "stage": ("machine", "機台操作", "chuck stage", "Vacuum chuck stage firmly holds the wafer during spinning.", "真空晶圓吸盤於高速旋轉加工時牢固吸附固定晶圓。"),
    "standard": ("workplace", "廠務交接", "standard protocol", "Execute every task according to company standard protocol.", "嚴格按照公司制定的標準規章手冊執行各項日常業務。"),
    "standby": ("machine", "機台操作", "tool on standby", "The tool is on standby waiting for the next lot.", "機台目前處於待機狀態，等待派工系統派送下一批貨。"),
    "start": ("machine", "機台操作", "press start", "Press start after verifying cassette slot mapping.", "再次核對晶圓片號圖譜無誤後，即可按下機台啟動鈕。"),
    "station": ("process", "晶圓製程", "work station", "Keep personal belongings outside the clean work station.", "個人私人物品嚴禁攜入無塵室專屬作業站點。"),
    "status": ("machine", "機台操作", "tool status", "Report any red tool status to the area leader.", "機台燈號若變為紅色停機狀態，請立刻向線長通報。"),
    "step": ("general", "基礎通用", "next step", "Verify parameters before advancing to the next step.", "推進至下一步驟前，請務必先驗證當前加工結果符合規定。"),
    "stocker": ("machine", "機台操作", "automated stocker", "Automated stocker stores and dispatches wafer cassettes.", "無塵室自動晶圓儲存倉負責自動化保管與派發晶圓盒。"),
    "success": ("general", "基礎通用", "successful test", "Engineering team celebrated the successful test run.", "工程與技術員團隊共同慶祝本次試產批次順利成功。"),
    "super": ("general", "基礎通用", "super clean", "Advanced fabs maintain a super clean manufacturing floor.", "先進晶圓廠始終維持著超越醫療級別的超純淨無塵環境。"),
    "super hot run": ("process", "晶圓製程", "super hot run lot", "Give super hot run lots immediate processing priority.", "特急件急單晶圓 (Super Hot Run) 享有最優先上機排程。"),
    "supervisor": ("workplace", "廠務交接", "shift supervisor", "Inform your shift supervisor about equipment downtime.", "機台發生不可排除之停機異常時，請迅速向輪班副理報告。"),
    "support": ("workplace", "廠務交接", "cross support", "Technicians provide mutual cross support during heavy shifts.", "產線繁忙出貨量大時，技術員同仁彼此發揮跨模組互相支援。"),
    "switch": ("machine", "機台操作", "toggle switch", "Toggle the manual switch only when prompted by GUI.", "僅在操作介面出現明確導引提示時才撥動特定實體開關。"),
    "system": ("machine", "機台操作", "MES system", "Record wafer transfer transactions in the MES system.", "晶圓盒各站移載交接均須確實於 MES 系統完成刷卡過帳。"),
    "tag": ("workplace", "廠務交接", "tag out", "Apply lock-out and tag-out before opening the tool panel.", "開啟機台維修蓋板前，務必確實落實上鎖掛牌 (LOTO) 規範。"),
    "take leave": ("workplace", "廠務交接", "apply to take leave", "Apply to take leave at least one week ahead of time.", "若欲請特別休假，請儘早於一週前循系統完成請假申請。"),
    "tape": ("process", "晶圓製程", "wafer dicing tape", "Apply protective tape on wafer backside before dicing.", "在晶圓切割道研磨作業前，需於晶圓背面貼合專用保護膠帶。"),
    "target": ("general", "基礎通用", "daily target", "Our shift achieved its daily target with high quality.", "本班技術團隊在兼顧高品質要求下圓滿達成今日產能目標。"),
    "technician": ("workplace", "廠務交接", "fab technician", "Fab technicians are essential to TSMC's manufacturing excellence.", "技術員是台積電維持全球卓越製造競爭力不可或缺的核心力量。"),
    "telephone": ("workplace", "廠務交接", "emergency telephone", "Pick up the clean room telephone to call extension 119.", "遇緊急狀況請立即拿起無塵室專用電話直撥廠內緊急分機。"),
    "temperature": ("machine", "機台操作", "control temperature", "The furnace chamber operates at a temperature over 800 degrees.", "擴散爐管內部維持高達八百度以上之超高溫運轉。"),
    "thickness": ("quality", "品質異常", "film thickness", "Measure oxide film thickness across forty-nine points.", "在整片晶圓均勻抽檢量測四十九點之氧化薄膜厚度。"),
    "thin film": ("process", "晶圓製程", "thin film deposition", "Thin film deposition adds microscopic insulating layers.", "薄膜沈積技術在矽晶圓表面生長微觀絕緣保護與導電膜層。"),
    "time": ("general", "基礎通用", "process time", "Total process time for this step is approximately forty minutes.", "本道站點處理流程之總加工時間約為四十分鐘。"),
    "title": ("general", "基礎通用", "job title", "His official job title is Senior Manufacturing Technician.", "他的正式職稱為台積電資深製造部技術員。"),
    "top": ("process", "晶圓製程", "top surface", "Never allow metallic tools to touch the wafer top surface.", "嚴禁任何金屬手工具直接觸碰晶圓正面電路區。"),
    "track": ("machine", "機台操作", "overhead track", "Overhead transport track conveys FOUP pods smoothly.", "天車天軌自動化搬運系統於高空軌道平穩快速運送晶圓盒。"),
    "training": ("workplace", "廠務交接", "safety training", "Complete mandatory safety training before entering fab.", "進入無塵室工作前，必須全數通過各項必修安全訓練考核。"),
    "trend": ("quality", "品質異常", "yield trend", "Analyze the weekly yield trend to detect minor anomalies.", "深入分析每週良率走勢圖，及早捕捉並撲滅潛在製程微異常。"),
    "tune": ("machine", "機台操作", "tune parameter", "Engineers tune RF power parameters to optimize etch rate.", "工程師微調射頻微波功率參數以達到最佳蝕刻速率。"),
    "turn rate": ("process", "晶圓製程", "spindle turn rate", "Maintain uniform spindle turn rate to ensure coating thickness.", "維持恆定均勻的旋塗轉速以保證光阻膜厚高度一致。"),
    "unload": ("machine", "機台操作", "unload cassette", "Unload the finished cassette and transfer it to the cart.", "將已完成之晶圓盒自裝載口小心卸下，並平穩放置於專用推車上。"),
    "use": ("general", "基礎通用", "use equipment", "Use equipment strictly in accordance with certified training.", "僅可在自身具備合格考核認證的授權機台範圍內進行操作。"),
    "username": ("machine", "機台操作", "enter username", "Enter your employee username to sign into the workstation.", "在工作站畫面鍵入個人員工帳號以完成身分驗證登入。"),
    "vendor": ("workplace", "廠務交接", "equipment vendor", "Escort the equipment vendor inside the clean room.", "設備原廠供應商工程師入廠檢修時須由廠內人員全程陪同。"),
    "view": ("general", "基礎通用", "view screen", "View the summary screen to verify recipe completion.", "檢視機台總結畫面以確認所有配方步驟均已順利完工。"),
    "wafer": ("process", "晶圓製程", "silicon wafer", "Handle each twelve-inch silicon wafer with maximum care.", "搬運與處理每一片十二吋矽晶圓時均須抱持最高等級謹慎。"),
    "waiting": ("machine", "機台操作", "waiting for lot", "The green light blinks indicating the tool is waiting for lot.", "綠色燈號規律閃爍表示機台目前正處於備便等料狀態。"),
    "warning": ("quality", "品質異常", "warning buzzer", "A loud warning buzzer sounded when the interlock tripped.", "當安全防護互鎖開關跳脫時，現場隨即響起高分貝蜂鳴警報。"),
    "weekly": ("workplace", "廠務交接", "weekly checklist", "Complete the weekly PM checklist before Friday afternoon.", "請務必於每週五下午前確實逐項填妥週保養點檢核對表。"),
    "wet": ("process", "晶圓製程", "wet bench", "Wear a full acid apron and face shield at the wet bench.", "於濕式化學清洗酸槽站作業時，務必著全套防酸圍裙與面罩。"),
    "window": ("process", "晶圓製程", "viewing window", "Look through the chamber viewing window to check plasma glow.", "透過真空腔體石英觀景視窗觀察電漿電弧輝光是否均勻。"),
    "yield": ("quality", "品質異常", "die yield", "Excellence in particle control directly boosts overall die yield.", "落實無塵室落塵微粒嚴密控管，能直接顯著提升晶圓良率。"),
    "zero": ("quality", "品質異常", "zero defect", "Our team strives every single shift for zero defect quality.", "全體輪班同仁在每一班別均齊心協力追求零缺陷之極致品質。"),
}

def main():
    json_path = os.path.join(os.path.dirname(__file__), "..", "tsmc-vocabulary.json")
    with open(json_path, "r", encoding="utf-8") as f:
        words = json.load(f)

    print(f"Total vocabulary words in JSON: {len(words)}")
    missing = []
    enriched_count = 0

    for item in words:
        w = item["word"]
        if w in ENRICH_MAP:
            cat, cat_label, phrase, sent, sent_meaning = ENRICH_MAP[w]
            item["category"] = cat
            item["categoryLabel"] = cat_label
            item["fabPhrase"] = phrase
            item["exampleSentence"] = sent
            item["exampleMeaning"] = sent_meaning
            enriched_count += 1
        else:
            missing.append(w)
            item["category"] = "general"
            item["categoryLabel"] = "基礎通用"
            item["fabPhrase"] = f"{w} in fab"
            item["exampleSentence"] = f"Pay attention to {w} during fab operation."
            item["exampleMeaning"] = f"在廠區作業中請注意 {item.get('meaning', w)}。"

    if missing:
        print(f"Warning: {len(missing)} words not explicitly in ENRICH_MAP: {missing}")
    else:
        print("All 288 words matched perfectly in ENRICH_MAP!")

    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(words, f, ensure_ascii=False, indent=2)

    print(f"Successfully saved enriched vocabulary to {json_path} ({enriched_count} enriched)!")

if __name__ == "__main__":
    main()
